<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Description>Данное приложение позволяет измерять интервалы времени с точностью до долей секунды.», авторские права сохранить за собой</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Sound\wow.mp3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Sound\wow.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
